routes/web.php
<?php

use App\Http\Controllers\FollowsController;
use App\Http\Controllers\PostsController;
use App\Http\Controllers\ProfilesController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

Route::resource('posts', PostsController::class)->except('show', 'index');
Route::get('/', [PostsController::class, 'index'])->name('posts.index');
Route::get('/profile/{user}/posts/{post}', [PostsController::class, 'show'])->name('posts.show');

Route::get('/profile/{user}', [ProfilesController::class, 'show'])->name('profile.show');
Route::get('/profile/{user}/edit', [ProfilesController::class, 'edit'])->name('profile.edit');
Route::put('/profile/{user}', [ProfilesController::class, 'update'])->name('profile.update');
Route::get('/profile/{user}/followers', [FollowsController::class, 'followers'])->name('profile.followers');
Route::get('/profile/{user}/following', [FollowsController::class, 'following'])->name('profile.following');

Route::post('follow/{user}', [FollowsController::class, 'store'])->name('profile.follow');

require __DIR__.'/auth.php';

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreatePostRequest;
use App\Models\Post;
use App\Models\User;
use Illuminate\Http\RedirectResponse;
use Illuminate\View\View;
use Intervention\Image\Facades\Image;

class PostsController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index(): View
    {
        $users = auth()->user()->following()->pluck('profiles.user_id');
        $posts = Post::whereIn('user_id', $users)->with('user')->latest()->paginate(5);
        return view('posts.index', compact(['posts']));
    }

    public function create(): View
    {
        return view('posts.create');
    }

    public function store(CreatePostRequest $request): RedirectResponse
    {
        $imagePath = $request->file('image')->store('images/posts');
        $image = Image::make(public_path("storage/{$imagePath}"))->fit(1200, 1200);
        $image->save();
        $post = Post::create([
            'caption' => $request->caption,
            'image' => $imagePath,
            'user_id' => auth()->id(),
        ]);
        session()->flash('success', 'Post Created Successfully!');
        return redirect(route('profile.show', ['user' => auth()->user()]));
    }

    public function show(User $user, Post $post): View
    {
        $follows = (auth()->user()) ? auth()->user()->following->contains($user->id) : false;
        return view('posts.show', compact(['user', 'post', 'follows']));
    }
}

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('main-content')
    <div class="container">
        <div class="row mt-5">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h2>Add New Post</h2>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('posts.store') }}" method="POST" enctype="multipart/form-data">
                            @csrf
                            <div class="form-group">
                                <label for="caption">Caption</label>
                                <input type="text"
                                    class="form-control @error('caption') is-invalid @enderror"
                                    id="caption"
                                    value="{{ old('caption') }}"
                                    name="caption"
                                    placeholder="Add Post Caption">
                                @error('caption')
                                    <small class="form-text text-danger">{{ $message }}</small>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label for="image">Image</label>
                                <input type="file" class="form-control @error('image') is-invalid @enderror" name="image" id="image">
                                @error('image')
                                    <small class="form-text text-danger">{{ $message }}</small>
                                @enderror
                            </div>

                            <button type="submit" class="btn btn-outline-success">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')

@section('page-level-styles')
    <style>
        .w-60 {
            max-width: 60px;
        }
    </style>
@endsection

@section('main-content')
    <div class="container">
        @foreach ($posts as $post)
            <div class="post mt-5 mb-5">
                <div class="row">
                    <div class="col-12 mb-3">
                        <div class="d-flex align-items-center">
                            <div class="pr-3">
                                <img src="{{ $post->user->profile->image == $post->user->gravatar_image ? $post->user->gravatar_image : asset('/storage/' . $post->user->profile->image) }}" alt="profile-image" class="rounded-circle w-100 w-60">
                            </div>
                            <div>
                                <div class="font-weight-bold">
                                    <a href="{{ route('profile.show', ['user' => $post->user]) }}">
                                        <span class="text-dark">{{ $post->user->username }}</span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-12">
                        <a href="{{ route('profile.show', ['user' => $post->user]) }}">
                            <img src="{{ asset('/storage/' . $post->image) }}" alt="Post" class="w-100">
                        </a>
                    </div>
                    <div class="col-12 mt-3">
                        <p>
                            <span class="font-weight-bold">
                                <a href="{{ route('profile.show', ['user' => $post->user]) }}">
                                    <span class="text-dark">{{ $post->user->username }}</span>
                                </a>
                            </span> {{ $post->caption }}
                        </p>
                        <small>Post Created: {{ $post->created_at->diffForHumans() }}</small>
                    </div>
                </div>
            </div>
            <hr>
        @endforeach
        @if($posts->isEmpty())
            <div class="row">
                <div class="col-12 mt-5">
                    <div class="alert text-center alert-primary" role="alert">
                        Follow Users To View Their Posts!
                    </div>
                </div>
            </div>
        @endif
        <div class="mt-5">
            {{ $posts->links('vendor.pagination.bootstrap-4') }}
        </div>
    </div>
@endsection

resources/views/posts/show.blade.php
@extends('layouts.app')

@section('page-level-styles')
    <style>
        .w-40 {
            max-width: 40px;
        }
    </style>
@endsection

@section('main-content')
    <div class="container">
        <div class="row mt-4">
            <div class="col-7">
                <img src="{{ asset('/storage/' . $post->image) }}" alt="Post" class="w-100">
            </div>
            <div class="col-5">
                <div class="d-flex align-items-center">
                    <div class="pr-3">
                        <img src="{{ $user->profile->image == $user->gravatar_image ? $user->gravatar_image : asset('/storage/' . $user->profile->image) }}" alt="profile-image" class="rounded-circle w-100 w-40">
                    </div>
                    <div>
                        <div class="font-weight-bold">
                            <a href="{{ route('profile.show', ['user' => $user]) }}">
                                <span class="text-dark">{{ $user->username }}</span>
                            </a>
                            @if($user->id != auth()->id())
                                <button class="btn btn-sm mr-auto ml-2 {{ $follows ? 'btn-outline-primary' : 'btn-primary' }}" id="followButton" onclick="follow({{ $user->id}})">{{ $follows ? 'Unfollow' : 'Follow' }}</button>
                            @endif
                        </div>
                    </div>
                </div>
                <hr>
                <p>
                    <span class="font-weight-bold">
                        <a href="{{ route('profile.show', ['user' => $user]) }}">
                            <span class="text-dark">{{ $post->user->username }}</span>
                        </a>
                    </span> {{ $post->caption }}
                </p>
                <small>Post Created: {{ $post->created_at->diffForHumans() }}</small>
            </div>
        </div>
    </div>
@endsection