routes/web.php
<?php

use App\Http\Controllers\FollowsController;
use App\Http\Controllers\PostsController;
use App\Http\Controllers\ProfilesController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

Route::resource('posts', PostsController::class)->except('show', 'index');
Route::get('/', [PostsController::class, 'index'])->name('posts.index');
Route::get('/profile/{user}/posts/{post}', [PostsController::class, 'show'])->name('posts.show');

Route::get('/profile/{user}', [ProfilesController::class, 'show'])->name('profile.show');
Route::get('/profile/{user}/edit', [ProfilesController::class, 'edit'])->name('profile.edit');
Route::put('/profile/{user}', [ProfilesController::class, 'update'])->name('profile.update');
Route::get('/profile/{user}/followers', [FollowsController::class, 'followers'])->name('profile.followers');
Route::get('/profile/{user}/following', [FollowsController::class, 'following'])->name('profile.following');

Route::post('follow/{user}', [FollowsController::class, 'store'])->name('profile.follow');

require __DIR__.'/auth.php';

app/Models/Profile.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Profile extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function followers()
    {
        return $this->belongsToMany(User::class)->with('profile');
    }
}

app/Http/Controllers/ProfilesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UpdateProfileRequest;
use App\Models\User;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Cache;
use Illuminate\View\View;
use Intervention\Image\Facades\Image;

class ProfilesController extends Controller
{
    public function show(User $user): View
    {
        $follows = (auth()->user()) ? auth()->user()->following->contains($user->id) : false;
        $followersCount = Cache::remember(
            'count.followers.' . $user->id,
            now()->addSeconds(10),
            function() use ($user) {
                return $user->profile->followers->count();
            }
        );
        $followingCount = Cache::remember(
            'count.following.' . $user->id,
            now()->addSeconds(10),
            function () use ($user) {
                return $user->following->count();
            }
        );
        return view('profiles.show', compact(['user', 'follows', 'followersCount', 'followingCount']));
    }

    public function edit(User $user): View
    {
        $this->authorize('update', $user->profile);
        return view('profiles.edit', compact(['user']));
    }

    public function update(UpdateProfileRequest $request, User $user): RedirectResponse
    {
        $this->authorize('update', $user->profile);
        $data = $request->only(['title', 'description', 'url']);
        if($request->hasFile('image')) {
            $imagePath = $request->file('image')->store('images/profiles');
            $image = Image::make(public_path("storage/{$imagePath}"))->fit(1200, 1200);
            $image->save();
            $data['image'] = $imagePath;
        }
        $user->profile->update($data);
        session()->flash('success', 'Profile Updated Successfully!');
        return redirect(route('profile.show', ['user' => auth()->user()]));
    }
}

resources/views/profiles/edit.blade.php
@extends('layouts.app')

@section('page-level-styles')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.css">
@endsection

@section('main-content')
    <div class="container">
        <div class="row mt-5">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h2>Edit Profile</h2>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('profile.update', ['user' => $user]) }}" method="POST" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <label for="title">Title</label>
                                <input type="hidden" id="title" name="title" value="{{old('title', $user->profile->title)}}">
                                <trix-editor input="title"></trix-editor>
                                @error('title')
                                    <small class="form-text text-danger">{{ $message }}</small>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label for="description">Description</label>
                                <input type="hidden" id="description" name="description" value="{{old('description', $user->profile->description)}}">
                                <trix-editor input="description"></trix-editor>
                                @error('description')
                                    <small class="form-text text-danger">{{ $message }}</small>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label for="url">URL</label>
                                <input type="text"
                                    class="form-control @error('url') is-invalid @enderror"
                                    id="url"
                                    value="{{ old('url', $user->profile->url) }}"
                                    name="url"
                                    placeholder="Enter URL">
                                @error('url')
                                    <small class="form-text text-danger">{{ $message }}</small>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label for="image">Profile Picture</label>
                                <input type="file" class="form-control @error('image') is-invalid @enderror" name="image" id="image">
                                @error('image')
                                    <small class="form-text text-danger">{{ $message }}</small>
                                @enderror
                            </div>

                            <button type="submit" class="btn btn-outline-success">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('page-level-scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.js"></script>
@endsection

resources/views/profiles/index.blade.php
@extends('layouts.app')

@section('page-level-styles')
    <style>
        .w-10 {
            width: 10%;
        }

        .image {
            display: block;
            margin: 0 auto;
        }

        a.deco-none {
            color: inherit;
            text-decoration:none;
        }
    </style>
@endsection

@section('main-content')
    <div class="container">
        @if($feature == "followers")
            <div class="row mt-4 mb-5">
                <div class="col-12 text-center">
                    <h1>{{ $user->username }}'s Followers</h1>
                </div>
            </div>
            @foreach($followers as $follower)
                <div class="row mt-4">
                    <div class="col-6">
                        <img src="{{ $follower->profile->image == $follower->gravatar_image ? $follower->gravatar_image : asset('/storage/' . $follower->profile->image) }}" alt="profile-image" class="rounded-circle img-fluid w-10 image">
                    </div>
                    <div class="col-6">
                        <a href="{{ route('profile.show', $follower) }}" class="deco-none h2">{{ $follower->username }}</a>
                    </div>
                </div>
                <hr>
            @endforeach
            @if($followers->isEmpty())
                <div class="row">
                    <div class="col-12 mt-5">
                        <div class="alert text-center alert-primary" role="alert">
                            This User Has No Followers!
                        </div>
                    </div>
                </div>
            @endif
        @elseif($feature == "following")
            <div class="row mt-4 mb-5">
                <div class="col-12 text-center">
                    <h1>{{ $user->username }}'s Following</h1>
                </div>
            </div>
            @foreach($followings as $following)
                <div class="row mt-4">
                    <div class="col-6">
                        <img src="{{ $following->image == $following->user->gravatar_image ? $following->user->gravatar_image : asset('/storage/' . $following->image) }}" alt="profile-image" class="rounded-circle img-fluid w-10 image">
                    </div>
                    <div class="col-6">
                        <a href="{{ route('profile.show', $following) }}" class="deco-none h2">{{ $following->user->username }}</a>
                    </div>
                </div>
                <hr>
            @endforeach
            @if($followings->isEmpty())
                <div class="row">
                    <div class="col-12 mt-5">
                        <div class="alert text-center alert-primary" role="alert">
                            This User Does Not Follow Anyone!
                        </div>
                    </div>
                </div>
            @endif
        @endif
    </div>
@endsection

resources/views/profiles/show.blade.php
@extends('layouts.app')

@section('page-level-styles')
    <style>
        .my-font {
            font-family: 'Noto Sans SC', sans-serif;
        }

        .image {
            display: block;
            max-width: 60%;
            margin: 0 auto;
        }

        .w-70 {
            width: 70%;
        }

        hr {
            background-color: #dddddd;
        }

        a.deco-none {
            color: inherit;
            text-decoration:none;
        }
    </style>
@endsection

@section('main-content')
    <div class="container">
        <div class="row mt-2">
            <div class="col-12">
                @include('layouts.partials._message')
            </div>
        </div>
        <div class="row mt-4 mb-4">
            <div class="col-3">
                <img src="{{ $user->profile->image == $user->gravatar_image ? $user->gravatar_image : asset('/storage/' . $user->profile->image) }}" alt="profile-image" class="rounded-circle img-fluid image">
            </div>
            <div class="col-9">
                <div class="ml-5">
                    <div class="d-flex align-items-center">
                        <h3 class="font-weight-light">{{ $user->username }}</h3>
                        @if($user->id == auth()->id())
                            <button class="btn btn-sm mr-auto ml-2">You</button>
                        @else
                            <button class="btn btn-sm mr-auto ml-2 {{ $follows ? 'btn-outline-primary' : 'btn-primary' }}" id="followButton" onclick="follow({{ $user->id}})">{{ $follows ? 'Unfollow' : 'Follow' }}</button>
                        @endif
                        @can('update', $user->profile)
                            <a href="{{ route('posts.create') }}" class="btn btn-primary btn-sm mr-2">New Post</a>
                        @endcan
                        @can('update', $user->profile)
                            <a href="{{ route('profile.edit', ['user' => $user]) }}" class="btn btn-secondary btn-sm">Edit Profile</a>
                        @endcan
                    </div>
                    <div class="d-flex">
                        <div class="pr-5">
                            <strong>{{ $user->getPostsCount() }}</strong> posts
                        </div>
                        <div class="pr-5">
                            <a href="{{ route('profile.followers', ['user' => $user]) }}" class="deco-none"><strong>{{ $followersCount }}</strong> followers</a>
                        </div>
                        <div class="pr-5">
                            <a href="{{ route('profile.following', ['user' => $user]) }}" class="deco-none"><strong>{{ $followingCount }}</strong> following</a>
                        </div>
                    </div>
                    <div class="mt-3 mb-1">
                        {!! $user->profile->title !!}
                    </div>
                    <div class="mt-1">
                        {!! $user->profile->description !!}
                    </div>
                    <p class="mb-2 mt-2"><a href="#">{{ $user->profile->url }}</a></p>
                </div>
            </div>
        </div>
        <hr>
        <div class="row">
            @foreach ($user->posts as $post)
                <div class="col-4 mt-3">
                    <a href="{{ route('posts.show', ['user' => $user, 'post' => $post]) }}">
                        <img class="w-100" src="{{ asset('/storage/' . $post->image) }}" alt="Post">
                    </a>
                </div>
            @endforeach
        </div>
    </div>
@endsection

@section('page-level-scripts')
    <script>
        function follow(userId) {
            $.ajax({
                type: 'POST',
                url: `/follow/${userId}`,
                data: {_token: '{{ csrf_token() }}' },
                success: function(data) {
                    if(data.follow) {
                        $("#followButton").text("Unfollow");
                        $("#followButton").addClass('btn-outline-primary');
                        $("#followButton").removeClass('btn-primary');
                        $("#followButton").blur();
                    } else {
                        $("#followButton").text("Follow");
                        $("#followButton").addClass('btn-primary');
                        $("#followButton").removeClass('btn-outline-primary');
                        $("#followButton").blur();
                    }
                },
                error: function(data) {
                    if(data.status == 401) {
                        let url = "{{ route('login') }}";
                        document.location.href = url;
                    }
                }
            });
        }
    </script>
@endsection